name: Populate gem cache

on:
  pull_request:
    paths:
      - .github/workflows/cache.yml
  push:
    paths:
      - .github/workflows/cache.yml
    branches:
      - main
  schedule:
    - cron: '30 19/6 * * *'
  workflow_dispatch:

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: cache-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  determine-runners:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/brew:main
    outputs:
      runners: ${{ steps.determine-runners.outputs.runners }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: false

      - name: Determine runners to use for this job
        id: determine-runners
        env:
          HOMEBREW_MACOS_TIMEOUT: 30
        # run: echo "runners=[{\"name\":\"Linux x86_64\",\"runner\":\"ubuntu-latest\",\"container\":{\"image\":\"ghcr.io/homebrew/brew:main\"},\"workdir\":\"/github/home\",\"timeout\":2160,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"Linux arm64\",\"runner\":\"ubuntu-22.04-arm\",\"container\":{\"image\":\"ghcr.io/homebrew/brew:main\"},\"timeout\":2160,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"macOS 26-arm64\",\"runner\":\"26-arm64-\",\"timeout\":60,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"macOS 26-x86_64\",\"runner\":\"26-x86_64-\",\"timeout\":120,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"macOS 15-arm64\",\"runner\":\"15-arm64-\",\"timeout\":60,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"macOS 15-x86_64\",\"runner\":\"15-x86_64-\",\"timeout\":120,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"macOS 14-arm64\",\"runner\":\"14-arm64-\",\"timeout\":60,\"cleanup\":false,\"testing_formulae\":\"\"},{\"name\":\"macOS 14-x86_64\",\"runner\":\"14-x86_64-\",\"timeout\":120,\"cleanup\":false,\"testing_formulae\":\"\"}]" >> "$GITHUB_OUTPUT"
        run: brew determine-test-runners python@3.14

  cache:
    needs: determine-runners
    strategy:
      matrix:
        include: ${{ fromJson(needs.determine-runners.outputs.runners) }}
      fail-fast: false
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    # container: ${{ matrix.container }}
    timeout-minutes: ${{ matrix.timeout }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: false

      - name: Cleanup runner
        if: matrix.cleanup
        working-directory: ${{ runner.temp }}
        run: brew test-bot --only-cleanup-before

      - name: Get cache key
        id: cache-key
        run: |
          cache_key_prefix="${{ runner.os }}"
          if [ "${{ runner.os }}" = macOS ]
          then
            macos_version="$(sw_vers -productVersion)"
            cache_key_prefix="${macos_version%%.*}-$(uname -m)"
          elif [ "${{ runner.os }}" == "Linux" ]
          then
            cache_key_prefix="linux-$(uname -m)"
          fi
          echo "prefix=${cache_key_prefix}" >> "${GITHUB_OUTPUT}"

      - name: Cache Homebrew Bundler gems
        uses: actions/cache@main
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ steps.cache-key.outputs.prefix }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ steps.cache-key.outputs.prefix }}-rubygems-

      - name: Setup Homebrew test environment
        working-directory: ${{ runner.temp }}
        run: brew test-bot --only-setup
